spring:
  mobile:
    devicedelegatingviewresolver:
      enabled: true
    sitepreference:
      enabled: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    suffix: .ftl

---
server:
  port: 8080
  contextPath: /
---
spring:
  profiles: prod
datasource:
  mzps:
    url: jdbc:mysql://localhost:3306/mzps
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

