spring:
  freemarker:
    cache: false
  jpa:
    database-platform: MYSQL
  profiles:
    active: production   #IMPORTANT! change to 'production' for production env database MySQL, and to 'development' for embedded h2 database
---
server:
  port: 8080
  contextPath: /
---
spring:
  profiles: production
  freemarker:
      cache: false
datasource:
  mzps:
    url: jdbc:mysql://localhost:3306/mzps
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update #unsafe for production env, better to write your own DML queries
      ddl-auto: update #also unsafe
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---

spring:
  profiles: development
  freemarker:
      cache: false
datasource:
  mzps:
    url: jdbc:h2:mem:testdbl;Mode=MySQL
    driverClassName: org.h2.Driver
    defaultSchema:
    hibernate:
      hbm2ddl.method: create
      ddl-auto: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect



